[env]
TERM = "alacritty"
# TERM = "xterm-256color"
# live_config_reload = true
[window]
padding = { x = 2, y = 4 }
dynamic_padding = true
decorations = "full"
# draw_bold_text_with_bright_colors = true

[font]
normal = { family = "MonoLisa Nerd Font", style = "Regular" }
# bold = { family = "MonoLisa Nerd Font", style = "Bold" }
# italic = { family = "MonoLisa Nerd Font", style = "Italic" }
# bold_italic = { family = "MonoLisa Nerd Font", style = "Bold Italic" }
# builtin_box_drawing = true
size = 15.0

[selection]
semantic_escape_chars = "',│`|:'\"()[]{}<>"
save_to_clipboard = false

[colors]
primary = { background = "0x282a36", foreground = "0xf8f8f2", bright_foreground = "0xffffff" }
cursor = { text = "0x282a36", cursor = "0xf8f8f2" }
vi_mode_cursor = { text = "CellBackground", cursor = "CellForeground" }
selection = { text = "CellForeground", background = "0x44475a" }
normal = { black = "0x21222c", red = "0xff5555", green = "0x50fa7b", yellow = "0xf1fa8c", blue = "0xbd93f9", magenta = "0xff79c6", cyan = "0x8be9fd", white = "0xf8f8f2" }
bright = { black = "0x6272a4", red = "0xff6e6e", green = "0x69ff94", yellow = "0xffffa5", blue = "0xd6acff", magenta = "0xff92df", cyan = "0xa4ffff", white = "0xffffff" }
search = { matches = { foreground = "0x44475a", background = "0x50fa7b" }, focused_match = { foreground = "0x44475a", background = "0xffb86c" } }
footer_bar = { background = "0x282a36", foreground = "0xf8f8f2" }
hints = { start = { foreground = "0x282a36", background = "0xf1fa8c" }, end = { foreground = "0xf1fa8c", background = "0x282a36" } }

[mouse]
hide_when_typing = true
