import = ["~/.config/alacritty/themes/horizon_dark.toml"]

[env]
TERM = "alacritty"

[window]
padding = { x = 2, y = 4 }
dynamic_padding = true
decorations = "full"
decorations_theme_variant = "Dark"
option_as_alt = "Both"

[font]
normal = { family = "MonoLisa",  style = "MonoLisa" }
builtin_box_drawing = true
size = 15.0

[selection]
semantic_escape_chars = "',│`|:'\"()[]{}<>"
save_to_clipboard = false

[mouse]
hide_when_typing = true
